### PR TITLE
fix(smart-wallet-sdk): add parseAddressDelegation

### LINKED ISSUE #340: smart-wallet-sdk: helper function for parsing active delegations

### LINKED ISSUE #341: smart-wallet-sdk: fetch transaction with authorization list, and parse out authorization

### PR DESCRIPTION
**Pull request by zhongeric**
Fix #340 
Fix #341 

## PR Scope

Please title your PR according to the following types and scopes following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/):

- `fix(SDK name):` will trigger a patch version
- `chore(<type>):` will not trigger any release and should be used for internal repo changes
- `<type>(public):` will trigger a patch version for non-code changes (e.g. README changes)
- `feat(SDK name):` will trigger a minor version
- `feat(breaking):` will trigger a major version for a breaking change

## Description

_[Summary of the change, motivation, and context]_

## How Has This Been Tested?

_[e.g. Manually, E2E tests, unit tests, Storybook]_

## Are there any breaking changes?

_[e.g. Type definitions, API definitions]_

If there are breaking changes, please ensure you bump the major version Bump the major version (by using the title `feat(breaking): ...`), post a notice in #eng-sdks, and explicitly notify all Uniswap Labs consumers of the SDK.

## (Optional) Feedback Focus

_[Specific parts of this PR you'd like feedback on, or that reviewers should pay closer attention to]_

## (Optional) Follow Ups

_[Things that weren't addressed in this PR, ways you plan to build on this work, or other ways this work could be extended]_

### CODE REVIEW

File: sdks/smart-wallet-sdk/src/utils/delegation.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import { Address, TransactionEIP7702 } from 'viem'
+import { recoverAuthorizationAddress, SignedAuthorization, SignedAuthorizationList } from 'viem/experimental'
+
+import { DELEGATION_MAGIC_PREFIX } from '../constants'
+
+export type RecoveredAuthorizationMap = Record<Address, SignedAuthorization>
+
+export class Delegation {
+    /**
+     * Receovers the signers of each authorization within the list sent in the transaction
```
Comment (snreynolds) [inline sdks/smart-wallet-sdk/src/utils/delegation.ts:10]:
```suggestion
     * Recovers the signers of each authorization within the list sent in the transaction
```

File: sdks/smart-wallet-sdk/src/utils/delegation.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+     * @dev this can also return just the contractAddress each signer is delegated to
+     * @param transaction : TransactionEIP7702
+     * @returns : Promise<RecoveredAuthorizationMap>
+     */
+    public static parseAuthorizationListFromTransaction(transaction: TransactionEIP7702): Promise<RecoveredAuthorizationMap> {
+        return this.parseAuthorizationList(transaction.authorizationList)
+    }
+
+    /**
+     * Receovers the signers of each authorization in the list
```
Comment (snreynolds) [inline sdks/smart-wallet-sdk/src/utils/delegation.ts:20]:
```suggestion
     * Recovers the signers of each authorization in the list
```

**Review by snreynolds — COMMENTED** [review]
only comment nits! looks good

File: sdks/smart-wallet-sdk/src/utils/delegation.ts [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+import { recoverAuthorizationAddress, SignedAuthorization, SignedAuthorizationList } from 'viem/experimental'
+
+import { DELEGATION_MAGIC_PREFIX } from '../constants'
+
+export type RecoveredAuthorizationMap = Record<Address, SignedAuthorization>
+
+export class Delegation {
+    /**
+     * Receovers the signers of each authorization within the list sent in the transaction
+     * @dev this can also return just the contractAddress each signer is delegated to
```
[the remark this answers is not in the document]
Comment (zhongeric) [reply sdks/smart-wallet-sdk/src/utils/delegation.ts:11]: yea i think we can leave for now and TAPI can use a viem provider to fetch the txn

**Review by snreynolds — APPROVED** [review]

**Review by dannythedawger — APPROVED** [review]
lgtm
